# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
