# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='draft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
