# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_remove_court_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='court',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 2, 5, 2, 5, 781909, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 2, 5, 2, 24, 719714, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
