# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20180206_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 6, 2, 59, 34, 39288, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
