# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 04:39
from __future__ import unicode_literals

import courts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20171212_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=courts.models.upload_location, width_field='width_field'),
        ),
    ]
