# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20180203_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.RemoveField(
            model_name='court',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='court',
            name='publish',
        ),
        migrations.AddField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 3, 20, 14, 1, 290204, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
