# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20180202_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='court',
            name='updated',
        ),
    ]
