# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20180202_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='court',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 3, 18, 8, 29, 322222, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 3, 18, 8, 35, 722274, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
