# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_court_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='content',
            field=models.CharField(default='', max_length=140),
        ),
    ]
