# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20180203_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='court',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 18, 15, 30, 52665, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
