# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 2, 2, 5, 35, 30, 344279, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 2, 5, 35, 38, 32337, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
