# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 06:35
from __future__ import unicode_literals

import courts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_image', models.ImageField(upload_to=courts.models.upload_location)),
                ('width_x', models.IntegerField()),
                ('width_y', models.IntegerField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.Court')),
            ],
        ),
    ]
