# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20180202_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterField(
            model_name='court',
            name='publish',
            field=models.DateField(null=True),
        ),
    ]
