# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_auto_20180202_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='court',
            name='publish',
        ),
    ]
