# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 06:58
from __future__ import unicode_literals

import courts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20180703_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=courts.models.upload_location, verbose_name='Image')),
                ('court', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courts.Court')),
            ],
        ),
    ]
