# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20180202_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 2, 2, 5, 45, 35, 915188, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
