# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_court_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
