# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 07:41
from __future__ import unicode_literals

import courts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=courts.models.upload_location, verbose_name='Photo'),
        ),
    ]
