# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_auto_20180809_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
