# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='image',
        ),
    ]
