# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forum_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='link',
            field=models.TextField(default=0),
        ),
    ]
