# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.URLField(),
        ),
    ]
