# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180601_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.URLField(default='https://'),
        ),
    ]
