# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180607_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='publish',
            field=models.DateField(auto_now=True),
        ),
    ]
