# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20180723_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
