# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
