# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180703_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
