# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180704_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=datetime.datetime(2018, 7, 26, 5, 49, 39, 646367, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
